spring.application.name=asistenciaService
#Datasource / Database
spring.datasource.url=jdbc:oracle:thin:@proyectolibroasistencia_high?TNS_ADMIN=src/main/resources/wallet/Wallet_proyectoLibroAsistencia
spring.datasource.username=ms_asistencia
spring.datasource.password=Microservicio_asistencia1
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true